### ISSUE TITLE
revert conversation thumbnail design to show title and snippet

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/landtalk#11]
We lost the original code for this.  The current design only shows the title and snippet when you rollover the image - we'd like it to appear below the image as in the old design (see file).
![conversation_design](https://user-images.githubusercontent.com/12202208/50925723-06ed0000-1408-11e9-87dd-74a13362954c.png)

**Comment by codyml** [comment]
Request: slightly increase type size or weight for place name titles.
