### ISSUE TITLE
Enable full text search for conversations

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/landtalk#12]

**Comment by codyml** [comment]
For this issue, change the WordPress API endpoint that performs text searches on Conversations to search other parts of the Conversation as well.  Given a search term, conversations should be returned when matches are found according to the following field priorities:

1. Title
2. Keywords
3. Narrative plain text fields
4. Transcript
5. Additional Info

So, for example, a conversation with a matching keyword will be ranked higher for relevance than a conversation with only a matching word in the transcript.  Furthermore, items with the same relevance should be returned in a random order.

This isn't a quick fix and will require pulling various data fields from WordPress and writing a PHP algorithm to perform the search and ranking.
