### ISSUE TITLE
Modify submission instructions

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/landtalk#20]
This will hopefully encourage people to do it more consistently...

Place Name (Required) *
Be as specific as possible. Include the full name of the place, city, state/province, and country. Do not use state or province abbreviations (although "USA" is preferred).

Example: Riverfront, Alton, Illinois, USA

Coordinates (Required) *
Enter the latitude and longitude of the place in decimal format. Be sure to include any negative signs (-). If possible, include at least 4 digits after the decimal point (for example, 48.40854).

To convert from hours-minutes-seconds format, use this tool.

To find coordinates of a location from Google Maps, zoom in until the place is easily distinguishable, then right-click on the place and select “What’s here?”. Then, copy and paste the latitude and longitude values from the resulting pop-up at the bottom of the screen.

Latitude *
Valid latitudes are between -90.0000 and 90.0000. Coordinates in southern hemisphere are negative!

Example: 42.84532

Longitude *
Valid longitudes are between -180.0000 and 180.0000. Coordinates in western hemisphere are negative!

Example: -122.34563

**Comment by codyml** [comment]
This task as completed in the live site's ACF database; need to move changes code.

**Comment by codyml** [comment]
Also, once live ACF database changes are moved into code, it might be a good idea to disable editing ACF fields on the live site so this doesn't happen again.
