### ISSUE TITLE
Make Grade Level/Age Field a drop-down 'age' menu

### ISSUE THREAD

**Issue by kcirerick** [cestastanford/landtalk#56]
Making this field a drop-down menu rather than a text-field will make ranking/sorting/filtering by age easier by having a uniform format.

**Comment by cartosattva** [comment]
Actually, I thought we decided not to do this. I think filtering by age is unlikely and I'd rather not restrict too much what people put into this field.

**Comment by kcirerick** [comment]
Sounds good, I’ll change it back.
