### ISSUE TITLE
Submission glitch when consent checkbox is not selected

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/landtalk#6]

**Comment by cartosattva** [comment]
Submitting the entry without consent deletes content from text fields, which is VERY frustrating if you have spent time working on it. Aside from fixing this potential bug, we should probably add some text somewhere that encourages people to prepare their entry offline since there is no way for users to to save and modify entries.

I experienced this issue I think when I had not selected the consent checkbox but submitted the entry while on a higher up section in the submission accordion (e.g. when the "Submission Details" section was collapsed).

**Comment by ada-zhou** [comment]
Cannot duplicate glitch
