### ISSUE TITLE
Widen all content on all pages to be 12/12 columns

### ISSUE THREAD

**Issue by codyml** [cestastanford/landtalk#60]
(except full-bleed content)

**Comment by codyml** [comment]
@kcirerick Hey just so you know, I assigned this one to myself when I opened it because I was working on it as part of the PR I'm about to submit.  I see you pushed a fix which looks good, but I was going to get rid of some unnecessary markup as part of fixing it so I'm going to reopen and re-close in my PR.

**Comment by codyml** [comment]
Also, for [this change](https://github.com/cestastanford/landtalk/commit/45671bf2c727c6642bbf9d45fbdbe51fe624c5d6#diff-4af962aaf19d1e6eb1c260d9ba1d087eR64), did you mean to change it to `is-12`?  If so, that would make every image a full 12 columns, which I think isn't what we want.  I'm going to revert that change but let me know if I misunderstood.

**Comment by kcirerick** [comment]
Yes, that's what I meant to do but maybe I misunderstood what the issue was. I also didn't realize you had assigned it to yourself, sorry about that.

**Comment by codyml** [comment]
@kcirerick No worries, happens all the time with distributed programming.  For the images, the `is-2` was applying to each individual image in the image strip; the whole container is full-bleed and not restricted to 10 or 12 columns.
