### ISSUE TITLE
Fix hard-coded page title in Lessons template

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/landtalk#9]

**Comment by codyml** [comment]
Headings are working as expected on most templates.  These templates use the WordPress page name as the heading:
 - Default Template (used for Privacy & Copyright)
 - About
 - Conversation Archive
 - Report Conversation
 - Submit Conversation
...while these pages drop the title for design reasons:
 - Home
 - Guidelines

However, the Lessons page has "Educational Resources" hard-coded as the page name.  Look at other templates from the first group above to see how the title should be retrieved and printed.
